[build]
  command = "pip install -r requirements.txt"
  publish = "templates"

# Direct deployment without functions
[[plugins]]
  package = "@netlify/plugin-python"

# API routes handled by your app.py directly
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200