[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "templates"

[build.environment]
  PYTHON_VERSION = "3.12"

# More specific API routing
[[redirects]]
  from = "/api*"
  to = "/.netlify/functions/app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/proxy*"
  to = "/.netlify/functions/proxy/:splat"
  status = 200
  force = true

# Static files
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200